[defaults]
output_dir = "./out"

[database]
server = "localhost"
port = 1433
user = "my_user"
password = "my_password"
database = "my_database"
driver = "ODBC Driver 18 for SQL Server"
trust_server_certificate = true